import UserModel from "../models/User.js";

const users = [
  {
    firstName: "Joli",
    lastName: "Folliott",
    username: "jfolliott0",
    email: "jfolliott0@google.co.uk",
    avatar: "https://robohash.org/beataequisaperiam.png?size=50x50&set=set1",
  },
  {
    firstName: "Dian",
    lastName: "Fort",
    username: "dfort1",
    email: "dfort1@t-online.de",
    avatar: "https://robohash.org/atminusimpedit.png?size=50x50&set=set1",
  },
  {
    firstName: "Genovera",
    lastName: "Risby",
    username: "grisby2",
    email: "grisby2@fastcompany.com",
    avatar:
      "https://robohash.org/voluptatumperferendisvoluptatibus.png?size=50x50&set=set1",
  },
  {
    firstName: "Lorinda",
    lastName: "de Clercq",
    username: "ldeclercq3",
    email: "ldeclercq3@networkadvertising.org",
    avatar:
      "https://robohash.org/adipisciaccusamussequi.png?size=50x50&set=set1",
  },
  {
    firstName: "Nadya",
    lastName: "Riddoch",
    username: "nriddoch4",
    email: "nriddoch4@odnoklassniki.ru",
    avatar: "https://robohash.org/velitquinisi.png?size=50x50&set=set1",
  },
  {
    firstName: "Amy",
    lastName: "Nutten",
    username: "anutten5",
    email: "anutten5@macromedia.com",
    avatar:
      "https://robohash.org/repudiandaevoluptatumsed.png?size=50x50&set=set1",
  },
  {
    firstName: "Annadiane",
    lastName: "Conti",
    username: "aconti6",
    email: "aconti6@tuttocitta.it",
    avatar: "https://robohash.org/doloremvelitimpedit.png?size=50x50&set=set1",
  },
  {
    firstName: "Dacia",
    lastName: "Jackways",
    username: "djackways7",
    email: "djackways7@google.nl",
    avatar:
      "https://robohash.org/occaecatimaximemolestiae.png?size=50x50&set=set1",
  },
  {
    firstName: "Elga",
    lastName: "Knath",
    username: "eknath8",
    email: "eknath8@technorati.com",
    avatar:
      "https://robohash.org/temporibusteneturmolestiae.png?size=50x50&set=set1",
  },
  {
    firstName: "Worth",
    lastName: "O'Bruen",
    username: "wobruen9",
    email: "wobruen9@washington.edu",
    avatar: "https://robohash.org/quasiplaceatsequi.png?size=50x50&set=set1",
  },
  {
    firstName: "Sigfrid",
    lastName: "Loach",
    username: "sloacha",
    email: "sloacha@drupal.org",
    avatar: "https://robohash.org/quasinumquamharum.png?size=50x50&set=set1",
  },
  {
    firstName: "Sallee",
    lastName: "Hammersley",
    username: "shammersleyb",
    email: "shammersleyb@mapquest.com",
    avatar: "https://robohash.org/quoullamrepellendus.png?size=50x50&set=set1",
  },
  {
    firstName: "Leoline",
    lastName: "Phillipp",
    username: "lphillippc",
    email: "lphillippc@va.gov",
    avatar: "https://robohash.org/etetdolorem.png?size=50x50&set=set1",
  },
  {
    firstName: "Viv",
    lastName: "Joiris",
    username: "vjoirisd",
    email: "vjoirisd@disqus.com",
    avatar: "https://robohash.org/harumquisquamdolor.png?size=50x50&set=set1",
  },
  {
    firstName: "Brana",
    lastName: "Janca",
    username: "bjancae",
    email: "bjancae@exblog.jp",
    avatar: "https://robohash.org/idofficiisab.png?size=50x50&set=set1",
  },
  {
    firstName: "Beale",
    lastName: "Ripsher",
    username: "bripsherf",
    email: "bripsherf@squidoo.com",
    avatar: "https://robohash.org/sitautnecessitatibus.png?size=50x50&set=set1",
  },
  {
    firstName: "Zitella",
    lastName: "Jannequin",
    username: "zjannequing",
    email: "zjannequing@discovery.com",
    avatar: "https://robohash.org/officiismagnamhic.png?size=50x50&set=set1",
  },
  {
    firstName: "Ruby",
    lastName: "Rapport",
    username: "rrapporth",
    email: "rrapporth@wordpress.org",
    avatar: "https://robohash.org/quiquiaest.png?size=50x50&set=set1",
  },
  {
    firstName: "Peter",
    lastName: "Milch",
    username: "pmilchi",
    email: "pmilchi@admin.ch",
    avatar: "https://robohash.org/impeditquasioptio.png?size=50x50&set=set1",
  },
  {
    firstName: "Sheree",
    lastName: "Phettiplace",
    username: "sphettiplacej",
    email: "sphettiplacej@techcrunch.com",
    avatar: "https://robohash.org/autoditaut.png?size=50x50&set=set1",
  },
  {
    firstName: "Tamarra",
    lastName: "Matoshin",
    username: "tmatoshink",
    email: "tmatoshink@friendfeed.com",
    avatar: "https://robohash.org/etutipsum.png?size=50x50&set=set1",
  },
  {
    firstName: "Lodovico",
    lastName: "Flemming",
    username: "lflemmingl",
    email: "lflemmingl@goo.ne.jp",
    avatar: "https://robohash.org/teneturquinam.png?size=50x50&set=set1",
  },
  {
    firstName: "Mabelle",
    lastName: "Panting",
    username: "mpantingm",
    email: "mpantingm@comcast.net",
    avatar: "https://robohash.org/etrationeearum.png?size=50x50&set=set1",
  },
  {
    firstName: "Jedediah",
    lastName: "Parlet",
    username: "jparletn",
    email: "jparletn@slideshare.net",
    avatar: "https://robohash.org/nobisquiqui.png?size=50x50&set=set1",
  },
  {
    firstName: "Milo",
    lastName: "Josland",
    username: "mjoslando",
    email: "mjoslando@cafepress.com",
    avatar: "https://robohash.org/quaequasqui.png?size=50x50&set=set1",
  },
  {
    firstName: "Latrena",
    lastName: "Dignan",
    username: "ldignanp",
    email: "ldignanp@tinypic.com",
    avatar: "https://robohash.org/reiciendisfugitqui.png?size=50x50&set=set1",
  },
  {
    firstName: "Elyn",
    lastName: "Petriello",
    username: "epetrielloq",
    email: "epetrielloq@lulu.com",
    avatar: "https://robohash.org/verodoloremquedicta.png?size=50x50&set=set1",
  },
  {
    firstName: "Lucila",
    lastName: "Hubback",
    username: "lhubbackr",
    email: "lhubbackr@businessweek.com",
    avatar:
      "https://robohash.org/dignissimosadipisciconsequuntur.png?size=50x50&set=set1",
  },
  {
    firstName: "Bonnee",
    lastName: "Maydwell",
    username: "bmaydwells",
    email: "bmaydwells@princeton.edu",
    avatar: "https://robohash.org/modiimpedittotam.png?size=50x50&set=set1",
  },
  {
    firstName: "Irita",
    lastName: "Foot",
    username: "ifoott",
    email: "ifoott@webs.com",
    avatar: "https://robohash.org/itaqueeumfugiat.png?size=50x50&set=set1",
  },
  {
    firstName: "Forster",
    lastName: "Loyd",
    username: "floydu",
    email: "floydu@state.tx.us",
    avatar: "https://robohash.org/nihilperferendisquia.png?size=50x50&set=set1",
  },
  {
    firstName: "Madel",
    lastName: "Fittes",
    username: "mfittesv",
    email: "mfittesv@walmart.com",
    avatar: "https://robohash.org/sitquiaassumenda.png?size=50x50&set=set1",
  },
  {
    firstName: "Lynnea",
    lastName: "Holcroft",
    username: "lholcroftw",
    email: "lholcroftw@prweb.com",
    avatar:
      "https://robohash.org/quamasperioresdeserunt.png?size=50x50&set=set1",
  },
  {
    firstName: "Nata",
    lastName: "Bosket",
    username: "nbosketx",
    email: "nbosketx@usa.gov",
    avatar: "https://robohash.org/exquiadipisci.png?size=50x50&set=set1",
  },
  {
    firstName: "Adam",
    lastName: "Kosel",
    username: "akosely",
    email: "akosely@liveinternet.ru",
    avatar:
      "https://robohash.org/molestiaedoloresrepellendus.png?size=50x50&set=set1",
  },
  {
    firstName: "Welby",
    lastName: "Goldman",
    username: "wgoldmanz",
    email: "wgoldmanz@soundcloud.com",
    avatar: "https://robohash.org/minimautqui.png?size=50x50&set=set1",
  },
  {
    firstName: "Mirella",
    lastName: "Thresh",
    username: "mthresh10",
    email: "mthresh10@yellowpages.com",
    avatar:
      "https://robohash.org/namlaboriosamquisquam.png?size=50x50&set=set1",
  },
  {
    firstName: "Kassia",
    lastName: "Oaker",
    username: "koaker11",
    email: "koaker11@bizjournals.com",
    avatar: "https://robohash.org/quidoloresin.png?size=50x50&set=set1",
  },
  {
    firstName: "Ree",
    lastName: "Blackster",
    username: "rblackster12",
    email: "rblackster12@topsy.com",
    avatar: "https://robohash.org/avoluptasearum.png?size=50x50&set=set1",
  },
  {
    firstName: "Robbie",
    lastName: "Burghill",
    username: "rburghill13",
    email: "rburghill13@alexa.com",
    avatar: "https://robohash.org/quaeratautet.png?size=50x50&set=set1",
  },
  {
    firstName: "Armstrong",
    lastName: "Joney",
    username: "ajoney14",
    email: "ajoney14@free.fr",
    avatar: "https://robohash.org/expeditafugacum.png?size=50x50&set=set1",
  },
  {
    firstName: "Bailie",
    lastName: "Carbert",
    username: "bcarbert15",
    email: "bcarbert15@tuttocitta.it",
    avatar: "https://robohash.org/quidemquaequos.png?size=50x50&set=set1",
  },
  {
    firstName: "Elvina",
    lastName: "Doogue",
    username: "edoogue16",
    email: "edoogue16@mtv.com",
    avatar: "https://robohash.org/sapientedictaofficia.png?size=50x50&set=set1",
  },
  {
    firstName: "Lib",
    lastName: "Sibbs",
    username: "lsibbs17",
    email: "lsibbs17@edublogs.org",
    avatar: "https://robohash.org/nambeataevoluptatum.png?size=50x50&set=set1",
  },
  {
    firstName: "Jackquelin",
    lastName: "Teas",
    username: "jteas18",
    email: "jteas18@cnn.com",
    avatar: "https://robohash.org/consecteturipsumsit.png?size=50x50&set=set1",
  },
  {
    firstName: "Corine",
    lastName: "Medmore",
    username: "cmedmore19",
    email: "cmedmore19@xinhuanet.com",
    avatar: "https://robohash.org/autemfugaeius.png?size=50x50&set=set1",
  },
  {
    firstName: "Hyacinthe",
    lastName: "Thomsson",
    username: "hthomsson1a",
    email: "hthomsson1a@tripadvisor.com",
    avatar: "https://robohash.org/errornemoiste.png?size=50x50&set=set1",
  },
  {
    firstName: "Sterne",
    lastName: "Kilgannon",
    username: "skilgannon1b",
    email: "skilgannon1b@blogger.com",
    avatar: "https://robohash.org/voluptasautemomnis.png?size=50x50&set=set1",
  },
  {
    firstName: "Susy",
    lastName: "Feathers",
    username: "sfeathers1c",
    email: "sfeathers1c@fotki.com",
    avatar: "https://robohash.org/inatquedelectus.png?size=50x50&set=set1",
  },
  {
    firstName: "Loreen",
    lastName: "Strowlger",
    username: "lstrowlger1d",
    email: "lstrowlger1d@canalblog.com",
    avatar: "https://robohash.org/hicautqui.png?size=50x50&set=set1",
  },
  {
    firstName: "Amii",
    lastName: "Wayvill",
    username: "awayvill1e",
    email: "awayvill1e@hexun.com",
    avatar: "https://robohash.org/adidquia.png?size=50x50&set=set1",
  },
  {
    firstName: "Lainey",
    lastName: "Crippill",
    username: "lcrippill1f",
    email: "lcrippill1f@oaic.gov.au",
    avatar: "https://robohash.org/liberonihilsint.png?size=50x50&set=set1",
  },
  {
    firstName: "Rafael",
    lastName: "Beachem",
    username: "rbeachem1g",
    email: "rbeachem1g@craigslist.org",
    avatar: "https://robohash.org/fugaautomnis.png?size=50x50&set=set1",
  },
  {
    firstName: "Hannah",
    lastName: "Bernhardsson",
    username: "hbernhardsson1h",
    email: "hbernhardsson1h@vkontakte.ru",
    avatar: "https://robohash.org/magnamofficiaut.png?size=50x50&set=set1",
  },
  {
    firstName: "Anjela",
    lastName: "Vittore",
    username: "avittore1i",
    email: "avittore1i@tripadvisor.com",
    avatar:
      "https://robohash.org/accusamusvoluptatesratione.png?size=50x50&set=set1",
  },
  {
    firstName: "Dianna",
    lastName: "Bulfoot",
    username: "dbulfoot1j",
    email: "dbulfoot1j@cdc.gov",
    avatar: "https://robohash.org/illumquibusdamrerum.png?size=50x50&set=set1",
  },
  {
    firstName: "Marina",
    lastName: "de Werk",
    username: "mdewerk1k",
    email: "mdewerk1k@wikispaces.com",
    avatar: "https://robohash.org/sequimagnamatque.png?size=50x50&set=set1",
  },
  {
    firstName: "Oberon",
    lastName: "McGarel",
    username: "omcgarel1l",
    email: "omcgarel1l@miibeian.gov.cn",
    avatar:
      "https://robohash.org/omnisrepellatcupiditate.png?size=50x50&set=set1",
  },
  {
    firstName: "Cull",
    lastName: "Methven",
    username: "cmethven1m",
    email: "cmethven1m@yellowbook.com",
    avatar: "https://robohash.org/eanihilut.png?size=50x50&set=set1",
  },
  {
    firstName: "Tandi",
    lastName: "Kiddle",
    username: "tkiddle1n",
    email: "tkiddle1n@vimeo.com",
    avatar: "https://robohash.org/autidvoluptatibus.png?size=50x50&set=set1",
  },
  {
    firstName: "Eberhard",
    lastName: "Redman",
    username: "eredman1o",
    email: "eredman1o@webeden.co.uk",
    avatar: "https://robohash.org/nonmagnamrepellendus.png?size=50x50&set=set1",
  },
  {
    firstName: "Moe",
    lastName: "Gunby",
    username: "mgunby1p",
    email: "mgunby1p@nhs.uk",
    avatar: "https://robohash.org/autemexcepturimagni.png?size=50x50&set=set1",
  },
  {
    firstName: "Rainer",
    lastName: "Bromige",
    username: "rbromige1q",
    email: "rbromige1q@narod.ru",
    avatar: "https://robohash.org/advelitatque.png?size=50x50&set=set1",
  },
  {
    firstName: "Dot",
    lastName: "Escofier",
    username: "descofier1r",
    email: "descofier1r@ebay.com",
    avatar:
      "https://robohash.org/accusantiumaperiamomnis.png?size=50x50&set=set1",
  },
  {
    firstName: "Joyous",
    lastName: "Hardiman",
    username: "jhardiman1s",
    email: "jhardiman1s@irs.gov",
    avatar: "https://robohash.org/quosanimiomnis.png?size=50x50&set=set1",
  },
  {
    firstName: "Horacio",
    lastName: "Farndell",
    username: "hfarndell1t",
    email: "hfarndell1t@phpbb.com",
    avatar: "https://robohash.org/distinctiositquae.png?size=50x50&set=set1",
  },
  {
    firstName: "Fina",
    lastName: "Harriskine",
    username: "fharriskine1u",
    email: "fharriskine1u@purevolume.com",
    avatar:
      "https://robohash.org/molestiasdebitismagni.png?size=50x50&set=set1",
  },
  {
    firstName: "Edgard",
    lastName: "Urey",
    username: "eurey1v",
    email: "eurey1v@umn.edu",
    avatar: "https://robohash.org/enimomnisminus.png?size=50x50&set=set1",
  },
  {
    firstName: "Marshall",
    lastName: "Augar",
    username: "maugar1w",
    email: "maugar1w@businessinsider.com",
    avatar: "https://robohash.org/eosnihilquia.png?size=50x50&set=set1",
  },
  {
    firstName: "Terry",
    lastName: "MacCague",
    username: "tmaccague1x",
    email: "tmaccague1x@msu.edu",
    avatar: "https://robohash.org/autemquiaet.png?size=50x50&set=set1",
  },
  {
    firstName: "Gunilla",
    lastName: "Vales",
    username: "gvales1y",
    email: "gvales1y@ezinearticles.com",
    avatar: "https://robohash.org/veniametrepellat.png?size=50x50&set=set1",
  },
  {
    firstName: "Melisent",
    lastName: "Kikke",
    username: "mkikke1z",
    email: "mkikke1z@psu.edu",
    avatar: "https://robohash.org/nonutcorrupti.png?size=50x50&set=set1",
  },
  {
    firstName: "Ram",
    lastName: "Vogelein",
    username: "rvogelein20",
    email: "rvogelein20@jimdo.com",
    avatar: "https://robohash.org/omnisofficiisea.png?size=50x50&set=set1",
  },
  {
    firstName: "Malachi",
    lastName: "Shalliker",
    username: "mshalliker21",
    email: "mshalliker21@xinhuanet.com",
    avatar: "https://robohash.org/excepturiinquas.png?size=50x50&set=set1",
  },
  {
    firstName: "Priscella",
    lastName: "McKinley",
    username: "pmckinley22",
    email: "pmckinley22@ning.com",
    avatar: "https://robohash.org/temporeadipisciet.png?size=50x50&set=set1",
  },
  {
    firstName: "Starla",
    lastName: "Tumilty",
    username: "stumilty23",
    email: "stumilty23@4shared.com",
    avatar: "https://robohash.org/quibusdamnullaodio.png?size=50x50&set=set1",
  },
  {
    firstName: "Taddeusz",
    lastName: "Gerling",
    username: "tgerling24",
    email: "tgerling24@e-recht24.de",
    avatar: "https://robohash.org/earumsitfacere.png?size=50x50&set=set1",
  },
  {
    firstName: "Ashlen",
    lastName: "Hustler",
    username: "ahustler25",
    email: "ahustler25@jalbum.net",
    avatar: "https://robohash.org/abutquae.png?size=50x50&set=set1",
  },
  {
    firstName: "Pamella",
    lastName: "Anchor",
    username: "panchor26",
    email: "panchor26@mayoclinic.com",
    avatar: "https://robohash.org/essesintoptio.png?size=50x50&set=set1",
  },
  {
    firstName: "Livy",
    lastName: "Gillies",
    username: "lgillies27",
    email: "lgillies27@ft.com",
    avatar: "https://robohash.org/quiistequis.png?size=50x50&set=set1",
  },
  {
    firstName: "Babita",
    lastName: "Shoreman",
    username: "bshoreman28",
    email: "bshoreman28@oracle.com",
    avatar:
      "https://robohash.org/illumveritatisvoluptate.png?size=50x50&set=set1",
  },
  {
    firstName: "Alysa",
    lastName: "Lammerich",
    username: "alammerich29",
    email: "alammerich29@amazon.de",
    avatar: "https://robohash.org/inmolestiaequibusdam.png?size=50x50&set=set1",
  },
  {
    firstName: "Jaimie",
    lastName: "Ballston",
    username: "jballston2a",
    email: "jballston2a@economist.com",
    avatar: "https://robohash.org/numquamvoluptassed.png?size=50x50&set=set1",
  },
  {
    firstName: "Rafaellle",
    lastName: "Taffarello",
    username: "rtaffarello2b",
    email: "rtaffarello2b@lycos.com",
    avatar: "https://robohash.org/dolormolestiaererum.png?size=50x50&set=set1",
  },
  {
    firstName: "Nessy",
    lastName: "Compfort",
    username: "ncompfort2c",
    email: "ncompfort2c@redcross.org",
    avatar: "https://robohash.org/maximenatusquasi.png?size=50x50&set=set1",
  },
  {
    firstName: "Aldon",
    lastName: "Botton",
    username: "abotton2d",
    email: "abotton2d@ycombinator.com",
    avatar: "https://robohash.org/quovelprovident.png?size=50x50&set=set1",
  },
  {
    firstName: "Rob",
    lastName: "Pottberry",
    username: "rpottberry2e",
    email: "rpottberry2e@prweb.com",
    avatar: "https://robohash.org/omnisdebitisiure.png?size=50x50&set=set1",
  },
  {
    firstName: "Hildy",
    lastName: "Sherman",
    username: "hsherman2f",
    email: "hsherman2f@tripod.com",
    avatar: "https://robohash.org/accusantiumnullafuga.png?size=50x50&set=set1",
  },
  {
    firstName: "Hastie",
    lastName: "Celler",
    username: "hceller2g",
    email: "hceller2g@shop-pro.jp",
    avatar:
      "https://robohash.org/placeatdoloresvoluptatum.png?size=50x50&set=set1",
  },
  {
    firstName: "Casey",
    lastName: "Ragborne",
    username: "cragborne2h",
    email: "cragborne2h@godaddy.com",
    avatar: "https://robohash.org/etutdoloremque.png?size=50x50&set=set1",
  },
  {
    firstName: "Zonnya",
    lastName: "Ferrolli",
    username: "zferrolli2i",
    email: "zferrolli2i@dion.ne.jp",
    avatar: "https://robohash.org/eaquevitaedolor.png?size=50x50&set=set1",
  },
  {
    firstName: "Laurie",
    lastName: "Chartman",
    username: "lchartman2j",
    email: "lchartman2j@sina.com.cn",
    avatar:
      "https://robohash.org/nihilexcepturinesciunt.png?size=50x50&set=set1",
  },
  {
    firstName: "Ashil",
    lastName: "Marushak",
    username: "amarushak2k",
    email: "amarushak2k@mit.edu",
    avatar: "https://robohash.org/eaquasiquo.png?size=50x50&set=set1",
  },
  {
    firstName: "Elbertine",
    lastName: "Wanley",
    username: "ewanley2l",
    email: "ewanley2l@java.com",
    avatar: "https://robohash.org/sintofficiisdebitis.png?size=50x50&set=set1",
  },
  {
    firstName: "Nert",
    lastName: "Corbert",
    username: "ncorbert2m",
    email: "ncorbert2m@xinhuanet.com",
    avatar: "https://robohash.org/autemidqui.png?size=50x50&set=set1",
  },
  {
    firstName: "Cristabel",
    lastName: "Constantinou",
    username: "cconstantinou2n",
    email: "cconstantinou2n@qq.com",
    avatar: "https://robohash.org/enimeumiusto.png?size=50x50&set=set1",
  },
  {
    firstName: "Tim",
    lastName: "Feeham",
    username: "tfeeham2o",
    email: "tfeeham2o@mayoclinic.com",
    avatar: "https://robohash.org/nonilloaut.png?size=50x50&set=set1",
  },
  {
    firstName: "Deana",
    lastName: "Vido",
    username: "dvido2p",
    email: "dvido2p@sun.com",
    avatar: "https://robohash.org/etvoluptatumofficiis.png?size=50x50&set=set1",
  },
  {
    firstName: "Carmelle",
    lastName: "Halbeard",
    username: "chalbeard2q",
    email: "chalbeard2q@theatlantic.com",
    avatar: "https://robohash.org/autconsequaturquas.png?size=50x50&set=set1",
  },
  {
    firstName: "Johnnie",
    lastName: "Franciottoi",
    username: "jfranciottoi2r",
    email: "jfranciottoi2r@umich.edu",
    avatar: "https://robohash.org/eossaepeeligendi.png?size=50x50&set=set1",
  },
  {
    firstName: "Trula",
    lastName: "Hucknall",
    username: "thucknall2s",
    email: "thucknall2s@ucla.edu",
    avatar: "https://robohash.org/evenietnullaenim.png?size=50x50&set=set1",
  },
  {
    firstName: "Kippy",
    lastName: "Reichelt",
    username: "kreichelt2t",
    email: "kreichelt2t@hao123.com",
    avatar: "https://robohash.org/delenitiindelectus.png?size=50x50&set=set1",
  },
  {
    firstName: "Sterne",
    lastName: "Goodfellow",
    username: "sgoodfellow2u",
    email: "sgoodfellow2u@amazonaws.com",
    avatar: "https://robohash.org/earumvoluptatemnihil.png?size=50x50&set=set1",
  },
  {
    firstName: "Gabbey",
    lastName: "Ebdin",
    username: "gebdin2v",
    email: "gebdin2v@techcrunch.com",
    avatar:
      "https://robohash.org/quaenumquamrepudiandae.png?size=50x50&set=set1",
  },
  {
    firstName: "Helene",
    lastName: "Rottcher",
    username: "hrottcher2w",
    email: "hrottcher2w@barnesandnoble.com",
    avatar: "https://robohash.org/amagnidebitis.png?size=50x50&set=set1",
  },
  {
    firstName: "Skell",
    lastName: "McGaugey",
    username: "smcgaugey2x",
    email: "smcgaugey2x@networkadvertising.org",
    avatar: "https://robohash.org/enimesttempore.png?size=50x50&set=set1",
  },
  {
    firstName: "Mick",
    lastName: "Currell",
    username: "mcurrell2y",
    email: "mcurrell2y@army.mil",
    avatar: "https://robohash.org/quiblanditiisveniam.png?size=50x50&set=set1",
  },
  {
    firstName: "Blair",
    lastName: "Francom",
    username: "bfrancom2z",
    email: "bfrancom2z@wix.com",
    avatar: "https://robohash.org/etquisalias.png?size=50x50&set=set1",
  },
  {
    firstName: "Temp",
    lastName: "Shemmin",
    username: "tshemmin30",
    email: "tshemmin30@tinyurl.com",
    avatar: "https://robohash.org/autquicumque.png?size=50x50&set=set1",
  },
  {
    firstName: "Bevvy",
    lastName: "Midghall",
    username: "bmidghall31",
    email: "bmidghall31@tamu.edu",
    avatar: "https://robohash.org/expeditaetdolor.png?size=50x50&set=set1",
  },
  {
    firstName: "Shem",
    lastName: "Bonavia",
    username: "sbonavia32",
    email: "sbonavia32@mtv.com",
    avatar: "https://robohash.org/officiisetasperiores.png?size=50x50&set=set1",
  },
  {
    firstName: "Damaris",
    lastName: "Fulmen",
    username: "dfulmen33",
    email: "dfulmen33@example.com",
    avatar: "https://robohash.org/sedsintqui.png?size=50x50&set=set1",
  },
  {
    firstName: "Jo ann",
    lastName: "Newnham",
    username: "jnewnham34",
    email: "jnewnham34@reference.com",
    avatar: "https://robohash.org/quiminimarepellat.png?size=50x50&set=set1",
  },
  {
    firstName: "Eddie",
    lastName: "Lendon",
    username: "elendon35",
    email: "elendon35@blogs.com",
    avatar: "https://robohash.org/quosesseeveniet.png?size=50x50&set=set1",
  },
  {
    firstName: "Corey",
    lastName: "McGavigan",
    username: "cmcgavigan36",
    email: "cmcgavigan36@exblog.jp",
    avatar: "https://robohash.org/eosquidemmollitia.png?size=50x50&set=set1",
  },
  {
    firstName: "Nolana",
    lastName: "Feldberger",
    username: "nfeldberger37",
    email: "nfeldberger37@sohu.com",
    avatar: "https://robohash.org/perferendiseumillo.png?size=50x50&set=set1",
  },
  {
    firstName: "Killy",
    lastName: "Manes",
    username: "kmanes38",
    email: "kmanes38@umn.edu",
    avatar: "https://robohash.org/sinttemporibuscum.png?size=50x50&set=set1",
  },
  {
    firstName: "Fredi",
    lastName: "Mewes",
    username: "fmewes39",
    email: "fmewes39@thetimes.co.uk",
    avatar:
      "https://robohash.org/voluptatumlaudantiumcupiditate.png?size=50x50&set=set1",
  },
  {
    firstName: "Flory",
    lastName: "Penhaleurack",
    username: "fpenhaleurack3a",
    email: "fpenhaleurack3a@time.com",
    avatar: "https://robohash.org/iustodistinctioporro.png?size=50x50&set=set1",
  },
  {
    firstName: "Hedda",
    lastName: "Borges",
    username: "hborges3b",
    email: "hborges3b@alibaba.com",
    avatar: "https://robohash.org/aliquamnondebitis.png?size=50x50&set=set1",
  },
  {
    firstName: "Hastings",
    lastName: "Wombwell",
    username: "hwombwell3c",
    email: "hwombwell3c@independent.co.uk",
    avatar: "https://robohash.org/quaeratquiaad.png?size=50x50&set=set1",
  },
  {
    firstName: "Rory",
    lastName: "Dimmock",
    username: "rdimmock3d",
    email: "rdimmock3d@instagram.com",
    avatar: "https://robohash.org/officiarerumquo.png?size=50x50&set=set1",
  },
  {
    firstName: "Brigitte",
    lastName: "Hellwich",
    username: "bhellwich3e",
    email: "bhellwich3e@reddit.com",
    avatar: "https://robohash.org/facereipsameum.png?size=50x50&set=set1",
  },
  {
    firstName: "Lauryn",
    lastName: "Marriott",
    username: "lmarriott3f",
    email: "lmarriott3f@archive.org",
    avatar:
      "https://robohash.org/voluptatemquisquamvoluptatem.png?size=50x50&set=set1",
  },
  {
    firstName: "Eldredge",
    lastName: "Oats",
    username: "eoats3g",
    email: "eoats3g@ca.gov",
    avatar:
      "https://robohash.org/perferendisametdebitis.png?size=50x50&set=set1",
  },
  {
    firstName: "Sarah",
    lastName: "Rumble",
    username: "srumble3h",
    email: "srumble3h@flickr.com",
    avatar: "https://robohash.org/doloremrepellatsit.png?size=50x50&set=set1",
  },
  {
    firstName: "Nickolas",
    lastName: "Baxendale",
    username: "nbaxendale3i",
    email: "nbaxendale3i@vkontakte.ru",
    avatar:
      "https://robohash.org/consecteturenimincidunt.png?size=50x50&set=set1",
  },
  {
    firstName: "Tobe",
    lastName: "Commucci",
    username: "tcommucci3j",
    email: "tcommucci3j@last.fm",
    avatar: "https://robohash.org/autetmollitia.png?size=50x50&set=set1",
  },
  {
    firstName: "Melodie",
    lastName: "Cuberley",
    username: "mcuberley3k",
    email: "mcuberley3k@yahoo.co.jp",
    avatar:
      "https://robohash.org/quisdignissimosaspernatur.png?size=50x50&set=set1",
  },
  {
    firstName: "Shaylynn",
    lastName: "Sheldrake",
    username: "ssheldrake3l",
    email: "ssheldrake3l@about.me",
    avatar: "https://robohash.org/maximedelectusfuga.png?size=50x50&set=set1",
  },
  {
    firstName: "Graehme",
    lastName: "Mannooch",
    username: "gmannooch3m",
    email: "gmannooch3m@nhs.uk",
    avatar:
      "https://robohash.org/distinctioexplicabolaboriosam.png?size=50x50&set=set1",
  },
  {
    firstName: "Edouard",
    lastName: "Kareman",
    username: "ekareman3n",
    email: "ekareman3n@fema.gov",
    avatar: "https://robohash.org/excepturieaquelibero.png?size=50x50&set=set1",
  },
  {
    firstName: "Kristina",
    lastName: "Sloan",
    username: "ksloan3o",
    email: "ksloan3o@microsoft.com",
    avatar: "https://robohash.org/namindignissimos.png?size=50x50&set=set1",
  },
  {
    firstName: "Ulrikaumeko",
    lastName: "Newbatt",
    username: "unewbatt3p",
    email: "unewbatt3p@cnbc.com",
    avatar: "https://robohash.org/pariaturculpadolorum.png?size=50x50&set=set1",
  },
  {
    firstName: "Rene",
    lastName: "Benfield",
    username: "rbenfield3q",
    email: "rbenfield3q@umn.edu",
    avatar: "https://robohash.org/namquasirepudiandae.png?size=50x50&set=set1",
  },
  {
    firstName: "Hastie",
    lastName: "Danks",
    username: "hdanks3r",
    email: "hdanks3r@purevolume.com",
    avatar:
      "https://robohash.org/providentrerumblanditiis.png?size=50x50&set=set1",
  },
  {
    firstName: "Roshelle",
    lastName: "Le Batteur",
    username: "rlebatteur3s",
    email: "rlebatteur3s@hostgator.com",
    avatar: "https://robohash.org/laboriosamsitodio.png?size=50x50&set=set1",
  },
  {
    firstName: "Frieda",
    lastName: "Safell",
    username: "fsafell3t",
    email: "fsafell3t@dyndns.org",
    avatar: "https://robohash.org/consequuntureosiste.png?size=50x50&set=set1",
  },
  {
    firstName: "Ardelia",
    lastName: "Dutchburn",
    username: "adutchburn3u",
    email: "adutchburn3u@comsenz.com",
    avatar: "https://robohash.org/explicabosapientesed.png?size=50x50&set=set1",
  },
  {
    firstName: "Caspar",
    lastName: "Tenbrug",
    username: "ctenbrug3v",
    email: "ctenbrug3v@clickbank.net",
    avatar: "https://robohash.org/assumendacumqueminus.png?size=50x50&set=set1",
  },
  {
    firstName: "Saba",
    lastName: "Coweuppe",
    username: "scoweuppe3w",
    email: "scoweuppe3w@nasa.gov",
    avatar: "https://robohash.org/estmolestiaeipsum.png?size=50x50&set=set1",
  },
  {
    firstName: "Wolf",
    lastName: "Dering",
    username: "wdering3x",
    email: "wdering3x@cbc.ca",
    avatar: "https://robohash.org/autquiapossimus.png?size=50x50&set=set1",
  },
  {
    firstName: "Darelle",
    lastName: "Sehorsch",
    username: "dsehorsch3y",
    email: "dsehorsch3y@technorati.com",
    avatar:
      "https://robohash.org/reprehenderitbeataesaepe.png?size=50x50&set=set1",
  },
  {
    firstName: "Tish",
    lastName: "Mustarde",
    username: "tmustarde3z",
    email: "tmustarde3z@elpais.com",
    avatar: "https://robohash.org/nesciuntnullaoptio.png?size=50x50&set=set1",
  },
  {
    firstName: "Crissie",
    lastName: "Bothams",
    username: "cbothams40",
    email: "cbothams40@craigslist.org",
    avatar: "https://robohash.org/autdeseruntunde.png?size=50x50&set=set1",
  },
  {
    firstName: "Adolpho",
    lastName: "Hayler",
    username: "ahayler41",
    email: "ahayler41@webnode.com",
    avatar: "https://robohash.org/possimushicrerum.png?size=50x50&set=set1",
  },
  {
    firstName: "Johnny",
    lastName: "Phant",
    username: "jphant42",
    email: "jphant42@dedecms.com",
    avatar: "https://robohash.org/ipsumsaepequisquam.png?size=50x50&set=set1",
  },
  {
    firstName: "Ann-marie",
    lastName: "Gudeman",
    username: "agudeman43",
    email: "agudeman43@house.gov",
    avatar: "https://robohash.org/iureexcepturitempora.png?size=50x50&set=set1",
  },
  {
    firstName: "Olwen",
    lastName: "Speedin",
    username: "ospeedin44",
    email: "ospeedin44@bandcamp.com",
    avatar: "https://robohash.org/estmaximesunt.png?size=50x50&set=set1",
  },
  {
    firstName: "Lorette",
    lastName: "Ash",
    username: "lash45",
    email: "lash45@rediff.com",
    avatar:
      "https://robohash.org/vitaefacerelaudantium.png?size=50x50&set=set1",
  },
  {
    firstName: "Mimi",
    lastName: "Cronkshaw",
    username: "mcronkshaw46",
    email: "mcronkshaw46@youtu.be",
    avatar: "https://robohash.org/repudiandaevelet.png?size=50x50&set=set1",
  },
  {
    firstName: "Heath",
    lastName: "Huxster",
    username: "hhuxster47",
    email: "hhuxster47@usda.gov",
    avatar: "https://robohash.org/porroaliquamet.png?size=50x50&set=set1",
  },
  {
    firstName: "Ronica",
    lastName: "Mitchard",
    username: "rmitchard48",
    email: "rmitchard48@seesaa.net",
    avatar:
      "https://robohash.org/sitdeseruntaccusantium.png?size=50x50&set=set1",
  },
  {
    firstName: "Michaelina",
    lastName: "Shillabear",
    username: "mshillabear49",
    email: "mshillabear49@blogs.com",
    avatar:
      "https://robohash.org/exercitationemcorporisaut.png?size=50x50&set=set1",
  },
  {
    firstName: "Nicolas",
    lastName: "Salliere",
    username: "nsalliere4a",
    email: "nsalliere4a@domainmarket.com",
    avatar: "https://robohash.org/dolormagnimolestiae.png?size=50x50&set=set1",
  },
  {
    firstName: "Ellen",
    lastName: "Kembley",
    username: "ekembley4b",
    email: "ekembley4b@foxnews.com",
    avatar: "https://robohash.org/autnumquamet.png?size=50x50&set=set1",
  },
  {
    firstName: "Monty",
    lastName: "Ertelt",
    username: "mertelt4c",
    email: "mertelt4c@telegraph.co.uk",
    avatar: "https://robohash.org/doloremsequicum.png?size=50x50&set=set1",
  },
  {
    firstName: "Esme",
    lastName: "Raywood",
    username: "eraywood4d",
    email: "eraywood4d@bravesites.com",
    avatar: "https://robohash.org/cupiditateiustocum.png?size=50x50&set=set1",
  },
  {
    firstName: "Frederick",
    lastName: "MacIlwrick",
    username: "fmacilwrick4e",
    email: "fmacilwrick4e@nsw.gov.au",
    avatar: "https://robohash.org/iuresapienteveniam.png?size=50x50&set=set1",
  },
  {
    firstName: "Tamarra",
    lastName: "Mecco",
    username: "tmecco4f",
    email: "tmecco4f@dropbox.com",
    avatar:
      "https://robohash.org/quibusdamdoloreexpedita.png?size=50x50&set=set1",
  },
  {
    firstName: "Ardine",
    lastName: "O'Glassane",
    username: "aoglassane4g",
    email: "aoglassane4g@canalblog.com",
    avatar:
      "https://robohash.org/facererecusandaedeleniti.png?size=50x50&set=set1",
  },
  {
    firstName: "Rowney",
    lastName: "Grealey",
    username: "rgrealey4h",
    email: "rgrealey4h@shinystat.com",
    avatar: "https://robohash.org/exesseeveniet.png?size=50x50&set=set1",
  },
  {
    firstName: "Darrelle",
    lastName: "Pernell",
    username: "dpernell4i",
    email: "dpernell4i@prweb.com",
    avatar:
      "https://robohash.org/quisnesciuntvoluptatum.png?size=50x50&set=set1",
  },
  {
    firstName: "Odele",
    lastName: "Hallowes",
    username: "ohallowes4j",
    email: "ohallowes4j@1und1.de",
    avatar:
      "https://robohash.org/consecteturrepellatculpa.png?size=50x50&set=set1",
  },
  {
    firstName: "Opal",
    lastName: "Olivazzi",
    username: "oolivazzi4k",
    email: "oolivazzi4k@sphinn.com",
    avatar: "https://robohash.org/sequimagniquae.png?size=50x50&set=set1",
  },
  {
    firstName: "Jacquenetta",
    lastName: "Vasler",
    username: "jvasler4l",
    email: "jvasler4l@ed.gov",
    avatar: "https://robohash.org/rerumvoluptaset.png?size=50x50&set=set1",
  },
  {
    firstName: "Orly",
    lastName: "Zealander",
    username: "ozealander4m",
    email: "ozealander4m@cmu.edu",
    avatar: "https://robohash.org/omnisitaqueab.png?size=50x50&set=set1",
  },
  {
    firstName: "Danya",
    lastName: "Gerhardt",
    username: "dgerhardt4n",
    email: "dgerhardt4n@biglobe.ne.jp",
    avatar: "https://robohash.org/odiomagniquae.png?size=50x50&set=set1",
  },
  {
    firstName: "Hildagarde",
    lastName: "Asker",
    username: "hasker4o",
    email: "hasker4o@deviantart.com",
    avatar:
      "https://robohash.org/laudantiumteneturnihil.png?size=50x50&set=set1",
  },
  {
    firstName: "Moshe",
    lastName: "Dartnall",
    username: "mdartnall4p",
    email: "mdartnall4p@springer.com",
    avatar: "https://robohash.org/saepetotamquae.png?size=50x50&set=set1",
  },
  {
    firstName: "Rolf",
    lastName: "Bissell",
    username: "rbissell4q",
    email: "rbissell4q@homestead.com",
    avatar: "https://robohash.org/recusandaeadomnis.png?size=50x50&set=set1",
  },
  {
    firstName: "Arielle",
    lastName: "Wisker",
    username: "awisker4r",
    email: "awisker4r@newyorker.com",
    avatar:
      "https://robohash.org/quiacupiditaterepellat.png?size=50x50&set=set1",
  },
  {
    firstName: "Iorgo",
    lastName: "Dainton",
    username: "idainton4s",
    email: "idainton4s@ucla.edu",
    avatar:
      "https://robohash.org/sintnumquamvoluptatem.png?size=50x50&set=set1",
  },
  {
    firstName: "Tiphanie",
    lastName: "Chalfont",
    username: "tchalfont4t",
    email: "tchalfont4t@webmd.com",
    avatar: "https://robohash.org/omnisfugasunt.png?size=50x50&set=set1",
  },
  {
    firstName: "Matt",
    lastName: "De Michele",
    username: "mdemichele4u",
    email: "mdemichele4u@fastcompany.com",
    avatar:
      "https://robohash.org/molestiaeofficiapariatur.png?size=50x50&set=set1",
  },
  {
    firstName: "Catrina",
    lastName: "Coath",
    username: "ccoath4v",
    email: "ccoath4v@tripadvisor.com",
    avatar: "https://robohash.org/earumexpeditaesse.png?size=50x50&set=set1",
  },
  {
    firstName: "Gerome",
    lastName: "Martin",
    username: "gmartin4w",
    email: "gmartin4w@about.me",
    avatar: "https://robohash.org/ullamundedeleniti.png?size=50x50&set=set1",
  },
  {
    firstName: "Jennine",
    lastName: "Dewicke",
    username: "jdewicke4x",
    email: "jdewicke4x@guardian.co.uk",
    avatar: "https://robohash.org/doloribusenimfacere.png?size=50x50&set=set1",
  },
  {
    firstName: "Willis",
    lastName: "Hebborne",
    username: "whebborne4y",
    email: "whebborne4y@engadget.com",
    avatar: "https://robohash.org/etmodifugiat.png?size=50x50&set=set1",
  },
  {
    firstName: "Lilly",
    lastName: "Monksfield",
    username: "lmonksfield4z",
    email: "lmonksfield4z@earthlink.net",
    avatar: "https://robohash.org/liberosequiatque.png?size=50x50&set=set1",
  },
  {
    firstName: "Jeramie",
    lastName: "Ilsley",
    username: "jilsley50",
    email: "jilsley50@nhs.uk",
    avatar: "https://robohash.org/natusetblanditiis.png?size=50x50&set=set1",
  },
  {
    firstName: "Kassey",
    lastName: "Ruf",
    username: "kruf51",
    email: "kruf51@jugem.jp",
    avatar: "https://robohash.org/eligendiutillum.png?size=50x50&set=set1",
  },
  {
    firstName: "Erick",
    lastName: "Scourfield",
    username: "escourfield52",
    email: "escourfield52@harvard.edu",
    avatar: "https://robohash.org/liberoutmaxime.png?size=50x50&set=set1",
  },
  {
    firstName: "Wyn",
    lastName: "Klimowicz",
    username: "wklimowicz53",
    email: "wklimowicz53@auda.org.au",
    avatar: "https://robohash.org/nobisexnisi.png?size=50x50&set=set1",
  },
  {
    firstName: "Deerdre",
    lastName: "Bourne",
    username: "dbourne54",
    email: "dbourne54@pinterest.com",
    avatar: "https://robohash.org/sapientequissint.png?size=50x50&set=set1",
  },
  {
    firstName: "Brand",
    lastName: "Brisco",
    username: "bbrisco55",
    email: "bbrisco55@shinystat.com",
    avatar: "https://robohash.org/molestiaeetalias.png?size=50x50&set=set1",
  },
  {
    firstName: "Wyndham",
    lastName: "Didball",
    username: "wdidball56",
    email: "wdidball56@huffingtonpost.com",
    avatar:
      "https://robohash.org/veritatisconsequaturet.png?size=50x50&set=set1",
  },
  {
    firstName: "Cobbie",
    lastName: "Bartusek",
    username: "cbartusek57",
    email: "cbartusek57@eventbrite.com",
    avatar: "https://robohash.org/modicommodidolorum.png?size=50x50&set=set1",
  },
  {
    firstName: "Marcello",
    lastName: "Aysh",
    username: "maysh58",
    email: "maysh58@plala.or.jp",
    avatar: "https://robohash.org/dolorerroriusto.png?size=50x50&set=set1",
  },
  {
    firstName: "Benoit",
    lastName: "Swait",
    username: "bswait59",
    email: "bswait59@mysql.com",
    avatar:
      "https://robohash.org/velitfacilisdoloremque.png?size=50x50&set=set1",
  },
  {
    firstName: "Gerome",
    lastName: "Baudic",
    username: "gbaudic5a",
    email: "gbaudic5a@oakley.com",
    avatar: "https://robohash.org/aametnihil.png?size=50x50&set=set1",
  },
  {
    firstName: "Donny",
    lastName: "O'Hickey",
    username: "dohickey5b",
    email: "dohickey5b@spotify.com",
    avatar: "https://robohash.org/rerumsapientenobis.png?size=50x50&set=set1",
  },
  {
    firstName: "Annnora",
    lastName: "Ambrogi",
    username: "aambrogi5c",
    email: "aambrogi5c@time.com",
    avatar: "https://robohash.org/voluptasidnatus.png?size=50x50&set=set1",
  },
  {
    firstName: "Carmelita",
    lastName: "Habbert",
    username: "chabbert5d",
    email: "chabbert5d@slideshare.net",
    avatar:
      "https://robohash.org/occaecaticonsequuntursint.png?size=50x50&set=set1",
  },
  {
    firstName: "Daven",
    lastName: "Hutchence",
    username: "dhutchence5e",
    email: "dhutchence5e@dmoz.org",
    avatar: "https://robohash.org/rerumcorruptimaiores.png?size=50x50&set=set1",
  },
  {
    firstName: "Clemmie",
    lastName: "Kiffin",
    username: "ckiffin5f",
    email: "ckiffin5f@youku.com",
    avatar: "https://robohash.org/doloremutcorporis.png?size=50x50&set=set1",
  },
  {
    firstName: "Orsa",
    lastName: "Abbatucci",
    username: "oabbatucci5g",
    email: "oabbatucci5g@123-reg.co.uk",
    avatar: "https://robohash.org/quaeratliberoaperiam.png?size=50x50&set=set1",
  },
  {
    firstName: "Ilysa",
    lastName: "World",
    username: "iworld5h",
    email: "iworld5h@comsenz.com",
    avatar: "https://robohash.org/aliquamquicorporis.png?size=50x50&set=set1",
  },
  {
    firstName: "Angus",
    lastName: "Pinnion",
    username: "apinnion5i",
    email: "apinnion5i@blogtalkradio.com",
    avatar: "https://robohash.org/iustoestest.png?size=50x50&set=set1",
  },
  {
    firstName: "Friedrich",
    lastName: "Rieger",
    username: "frieger5j",
    email: "frieger5j@infoseek.co.jp",
    avatar: "https://robohash.org/inetvoluptas.png?size=50x50&set=set1",
  },
];

const seedUsers = () => {
  users.map(
    async ({ firstName, lastName, username, email, avatar }) =>
      await UserModel.create({ firstName, lastName, username, email, avatar }),
  );
};

export default seedUsers;
